"""Data loading, preprocessing, splitting, and dataset utilities."""

import random
from pathlib import Path

import numpy as np
import pandas as pd
import torch
from torch.utils.data import DataLoader, Dataset

SEED = 42
PAD_TOKEN = "<pad>"
UNK_TOKEN = "<unk>"


def set_seed(seed: int = SEED):
    random.seed(seed)
    np.random.seed(seed)


def load_raw_data(data_dir: str):
    """Load processed recommender files generated by data/get_data.py."""
    data_root = Path(data_dir)
    items_path = data_root / "processed" / "items.csv"
    impressions_path = data_root / "processed" / "impressions.csv"

    if not items_path.exists() or not impressions_path.exists():
        raise FileNotFoundError(
            f"Missing required files at {items_path} / {impressions_path}. "
            "Run `python data/get_data.py` first."
        )

    items = pd.read_csv(items_path)
    impressions = pd.read_csv(impressions_path)
    return items, impressions


def _expand_impressions(items: pd.DataFrame, impressions: pd.DataFrame) -> pd.DataFrame:
    item_text = items.set_index("item_id")["text"].to_dict()
    rows = []
    for row in impressions.itertuples(index=False):
        candidate_ids = [int(x) for x in str(row.candidate_item_ids).split()]
        clicked = int(row.clicked_item_id)
        user_context = f"user prefers {row.user_pref}"
        for item_id in candidate_ids:
            rows.append(
                {
                    "impression_id": int(row.impression_id),
                    "user_id": int(row.user_id),
                    "item_id": int(item_id),
                    "label": float(item_id == clicked),
                    "combined_text": f"{user_context} [SEP] {item_text.get(item_id, '')}",
                }
            )
    return pd.DataFrame(rows)


def preprocess(items: pd.DataFrame, impressions: pd.DataFrame) -> pd.DataFrame:
    """Create model-ready training rows from impression candidate lists."""
    df = _expand_impressions(items=items, impressions=impressions)
    df["combined_text"] = df["combined_text"].astype(str).str.lower()
    return df


def split_data(df: pd.DataFrame, train: float = 0.7, val: float = 0.15, test: float = 0.15):
    """Temporal split by impression id to avoid leakage across train/val/test."""
    assert abs(train + val + test - 1.0) < 1e-6, "Splits must sum to 1."

    ordered_impressions = sorted(df["impression_id"].unique().tolist())
    n = len(ordered_impressions)
    train_end = int(n * train)
    val_end = train_end + int(n * val)

    train_ids = set(ordered_impressions[:train_end])
    val_ids = set(ordered_impressions[train_end:val_end])
    test_ids = set(ordered_impressions[val_end:])

    train_df = df[df["impression_id"].isin(train_ids)].reset_index(drop=True)
    val_df = df[df["impression_id"].isin(val_ids)].reset_index(drop=True)
    test_df = df[df["impression_id"].isin(test_ids)].reset_index(drop=True)
    return train_df, val_df, test_df


def build_vocab(texts: pd.Series, min_freq: int = 1) -> dict:
    """Build a simple whitespace vocabulary."""
    freq = {}
    for text in texts:
        for tok in str(text).split():
            freq[tok] = freq.get(tok, 0) + 1

    vocab = {PAD_TOKEN: 0, UNK_TOKEN: 1}
    for token, count in sorted(freq.items()):
        if count >= min_freq:
            vocab[token] = len(vocab)
    return vocab


def encode_text(text: str, vocab: dict, max_len: int = 48) -> list:
    ids = [vocab.get(tok, vocab[UNK_TOKEN]) for tok in str(text).split()][:max_len]
    if len(ids) < max_len:
        ids.extend([vocab[PAD_TOKEN]] * (max_len - len(ids)))
    return ids


class RecommenderDataset(Dataset):
    """PyTorch dataset for click prediction from ranking candidates."""

    def __init__(self, df: pd.DataFrame, vocab: dict, max_len: int = 48):
        self.df = df
        self.vocab = vocab
        self.max_len = max_len

    def __len__(self):
        return len(self.df)

    def __getitem__(self, idx):
        row = self.df.iloc[idx]
        token_ids = encode_text(row["combined_text"], self.vocab, max_len=self.max_len)
        return {
            "input_ids": torch.tensor(token_ids, dtype=torch.long),
            "label": torch.tensor(float(row["label"]), dtype=torch.float32),
            "impression_id": torch.tensor(int(row["impression_id"]), dtype=torch.long),
            "item_id": torch.tensor(int(row["item_id"]), dtype=torch.long),
        }


def get_dataloader(df: pd.DataFrame, vocab: dict, batch_size: int = 32, shuffle: bool = True, max_len: int = 48):
    dataset = RecommenderDataset(df=df, vocab=vocab, max_len=max_len)
    return DataLoader(dataset, batch_size=batch_size, shuffle=shuffle)
