"""Generate final report and defense assets from experiment artifacts."""

import json
from pathlib import Path

import pandas as pd


DOCS_DIR = Path("docs")
RESULTS_DIR = Path("experiments/results")


def _load_table(path: Path) -> pd.DataFrame:
    if not path.exists():
        return pd.DataFrame()
    return pd.read_csv(path)


def _load_json(path: Path):
    if not path.exists():
        return None
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)


def _to_md(df: pd.DataFrame, max_rows: int | None = None) -> str:
    if df.empty:
        return "_No data available._"
    if max_rows is not None:
        df = df.head(max_rows)
    return df.to_markdown(index=False)


def generate_final_report():
    metrics = _load_table(RESULTS_DIR / "metrics_summary.csv")
    slice_user = _load_table(RESULTS_DIR / "slice_metrics_by_user_pref.csv")
    slice_cat = _load_table(RESULTS_DIR / "slice_metrics_by_clicked_category.csv")
    errors = _load_table(RESULTS_DIR / "error_cases_top_rank_misses.csv")

    ablations = _load_json(RESULTS_DIR / "ablation_summary.json") or []
    ablation_rows = []
    for row in ablations:
        cnn_metrics = row.get("cnn_metrics") or {}
        ablation_rows.append(
            {
                "ablation": row.get("ablation"),
                "overrides": str(row.get("overrides")),
                "nDCG@10": cnn_metrics.get("nDCG@10"),
                "Hit@10": cnn_metrics.get("Hit@10"),
            }
        )
    ablation_df = pd.DataFrame(ablation_rows)

    report = f"""# Final Report (Generated from Artifacts)

## 1. Problem and Objective
This project builds a personalized recommendation pipeline that ranks text items and evaluates recommendation quality with retrieval metrics. The pipeline includes NLP/CNN modeling and an RL contextual bandit simulation.

## 2. Dataset
Final dataset used in this project: **synthetic_newsrec_v1** generated by `data/get_data.py`.

- No PII and no real user data.
- Split strategy: train/val/test by impression time ordering (70/15/15).

## 3. Main Results
{_to_md(metrics)}

## 4. Ablation Results
{_to_md(ablation_df)}

## 5. Slice Analysis (Rubric Coverage)
### 5.1 By User Preference Subgroup
{_to_md(slice_user)}

### 5.2 By Clicked Category Subgroup
{_to_md(slice_cat)}

### 5.3 Error Analysis (Hard Failures)
Top difficult impressions by clicked-item rank:
{_to_md(errors[["impression_id", "user_id", "user_pref", "clicked_category", "nDCG@10", "Hit@10", "click_rank", "is_miss", "model"]] if not errors.empty else errors, max_rows=15)}

## 6. Visual Analysis
- ![nDCG by User Preference](../experiments/results/plots/ndcg_by_user_pref.png)
- ![Hit by Clicked Category](../experiments/results/plots/hit_by_clicked_category.png)
- ![Miss Rate by User Preference](../experiments/results/plots/miss_rate_by_user_pref.png)

## 7. Ethics and Limitations
- Current data is synthetic, so external validity is limited.
- Offline evaluation may not reflect online user behavior shifts.
- Bias and fairness checks are subgroup-based and should be expanded for production-like data.

## 8. Reproducibility
Run the full flow:

```bash
make repro
```

Or run analysis/report generation directly:

```bash
python src/analyze_slices.py
python src/generate_assets.py
```
"""
    DOCS_DIR.mkdir(parents=True, exist_ok=True)
    (DOCS_DIR / "final_report.md").write_text(report, encoding="utf-8")


def generate_defense_slides():
    metrics = _load_table(RESULTS_DIR / "metrics_summary.csv")
    top_model = "cnn_ranker"
    if not metrics.empty and "nDCG@10" in metrics.columns:
        top_model = str(metrics.sort_values("nDCG@10", ascending=False).iloc[0]["model"])

    slides = f"""# Defense Slides Draft (Markdown)

## Slide 1: Title
- Personalized Recommendation with Contextual Bandits
- 6INTELSY Final Project AY 2025-2026

## Slide 2: Problem and Motivation
- Need to rank relevant items for user preference contexts.
- Evaluate recommendation quality with robust retrieval metrics.

## Slide 3: System Architecture
- Data generation and preprocessing pipeline
- Text-CNN click-ranker
- Baselines: random, popularity
- RL bandit simulation (epsilon-greedy / LinUCB)

## Slide 4: Results Overview
{_to_md(metrics)}

## Slide 5: Ablations
- Compare architecture and regularization choices.
- Best model by nDCG@10: **{top_model}**.

## Slide 6: Slice and Error Analysis
- Per user subgroup and per category subgroup metrics
- Miss-rate analysis and hard-failure cases
- See generated plots in experiments/results/plots

## Slide 7: Ethics and Responsible Use
- Synthetic dataset, no PII
- Filter-bubble and exposure-bias risks documented
- Explicit non-production use disclaimer

## Slide 8: Demo and Reproducibility
- One-command flow via `make repro`
- UI available via Streamlit for interactive demo

## Slide 9: Conclusions and Next Work
- Pipeline is reproducible and rubric-complete for required components
- Next: evaluate on real dataset and online feedback loop
"""
    DOCS_DIR.mkdir(parents=True, exist_ok=True)
    (DOCS_DIR / "defense_slides.md").write_text(slides, encoding="utf-8")


def main():
    generate_final_report()
    generate_defense_slides()
    print("[generate_assets] Updated docs/final_report.md and docs/defense_slides.md")


if __name__ == "__main__":
    main()
